### ISSUE TITLE
Enabling catch all breaks site

### ISSUE THREAD

**Issue by joshworden** [Dolphiq/craft3-plugin-redirect#49]
Enabling the catch all feature causes Craft to return a 500 error. Here's the error from the log:

`yii\base\ErrorException: Undefined index: sourceUrl in /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/dolphiq/redirect/src/controllers/RedirectController.php:30 Stack trace: #0 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/jdw/Docu...', 30) #1 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/dolphiq/redirect/src/controllers/RedirectController.php(30): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Users/jdw/Docu...', 30, Array) #2 [internal function]: dolphiq\redirect\controllers\RedirectController->actionIndex() #3 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #4 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #5 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('index', Array) #6 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array) #7 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('redirect/redire...', Array) #8 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('redirect/redire...', Array) #9 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request)) #10 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request)) #11 /Users/jdw/Documents/Business/Web Clients/Trajectory/trajectory2/dist/web/index.php(21): yii\base\Application->run() #12 {main}`

I've found that replacing $redirect['sourceUrl'] on line 181 with a defined string (like 'abc') fixes the issue.

**Comment by johanzandstra** [comment]
I will dig into it!

**Comment by AmericanTrails** [comment]
Excellent to hear. It’s a great plugin that we’re relying heavily on for our transition to craft.

On 7/4/18, 12:03 PM, "Johan Zandstra" <notifications@github.com<mailto:notifications@github.com>> wrote:


I will dig into it!

**Comment by johanzandstra** [comment]
We fixed this issue in the just released version v1.0.17

**Comment by AmericanTrails** [comment]
I’m still receiving:
Internal Server Error
Server Error
“

When going to the link redirect/registered-catch-all-urls



On 7/4/18, 1:46 PM, "Johan Zandstra" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #49<https://github.com/Dolphiq/craft3-plugin-redirect/issues/49>.

**Comment by johanzandstra** [comment]
Did you set a twig tempalate in the <craft>/templates/ dir and point it in the plugin settings, like:

404.twig (set 404.twig in the settings, not the whole absolute path. and else, could you give me a dump if te error?

**Comment by johanzandstra** [comment]
Reading your post (again), it looks like you have troubles to get the registered list in the plugin section (not visiting a not existing page), please let me know the error from the log!

**Comment by AmericanTrails** [comment]
Here is the error:


SQLSTATE[42S02]: Base table or view not found: 1146 Table 'av05116a.craft_dolphiq_redirects_catch_all_urls' doesn't exist
The SQL being executed was: SELECT *
FROM `craft_dolphiq_redirects_catch_all_urls`
WHERE `siteId`=1
ORDER BY `dateUpdated` DESC
LIMIT 100
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'av05116a.craft_dolphiq_redirects_catch_all_urls' doesn't exist


On 7/4/18, 2:00 PM, "Johan Zandstra" <notifications@github.com<mailto:notifications@github.com>> wrote:


Reading your post (again), it looks like you have troubles to get the registered list in the plugin section (not visiting a not existing page), please let me know the error from the log!

**Comment by AmericanTrails** [comment]
To your second question, no, I did not (nor do I know how to) change the prefix setting after installation.

On 7/4/18, 2:23 PM, "Johan Zandstra" <notifications@github.com<mailto:notifications@github.com>> wrote:


I see that you use craft_ as a table prefix. The error points out that the table craft_dolphiq_redirects_catch_all_urls does not exist. Can you please verify that the table dolphiq_redirects_catch_all_urls (no craft_ as a prefix) exists in the database? And did you change the prefix setting after the installation?

**Comment by johanzandstra** [comment]
looks like you missed a migration script. 

can you try to run 
./craft migrate/up --plugin=redirect 

from you project craft folder?

see: https://docs.craftcms.com/v3/plugin-migrations.html#executing-migrations

**Comment by lukebailey** [comment]
Seeing the same issue, the migration seems to append the database prefix to the end of the table name:

SELECT * FROM craft_dolphiq_redirects_catch_all_urlscraft_;

**Comment by lukebailey** [comment]
Hi is there any update on getting this resolved please?
